/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The certificate merge parameters
    /// </summary>
    [DataContract]
    public partial class CertificateMergeParameters :  IEquatable<CertificateMergeParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateMergeParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CertificateMergeParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CertificateMergeParameters" /> class.
        /// </summary>
        /// <param name="X5c">The certificate or the certificate chain to merge. (required).</param>
        /// <param name="Attributes">The attributes of the certificate (optional)..</param>
        /// <param name="Tags">Application specific metadata in the form of key-value pairs..</param>
        public CertificateMergeParameters(List<byte[]> X5c = default(List<byte[]>), CertificateAttributes Attributes = default(CertificateAttributes), Dictionary<string, string> Tags = default(Dictionary<string, string>))
        {
            // to ensure "X5c" is required (not null)
            if (X5c == null)
            {
                throw new InvalidDataException("X5c is a required property for CertificateMergeParameters and cannot be null");
            }
            else
            {
                this.X5c = X5c;
            }
            this.Attributes = Attributes;
            this.Tags = Tags;
        }
        
        /// <summary>
        /// The certificate or the certificate chain to merge.
        /// </summary>
        /// <value>The certificate or the certificate chain to merge.</value>
        [DataMember(Name="x5c", EmitDefaultValue=false)]
        public List<byte[]> X5c { get; set; }

        /// <summary>
        /// The attributes of the certificate (optional).
        /// </summary>
        /// <value>The attributes of the certificate (optional).</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public CertificateAttributes Attributes { get; set; }

        /// <summary>
        /// Application specific metadata in the form of key-value pairs.
        /// </summary>
        /// <value>Application specific metadata in the form of key-value pairs.</value>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CertificateMergeParameters {\n");
            sb.Append("  X5c: ").Append(X5c).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as CertificateMergeParameters);
        }

        /// <summary>
        /// Returns true if CertificateMergeParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of CertificateMergeParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CertificateMergeParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.X5c == other.X5c ||
                    this.X5c != null &&
                    this.X5c.SequenceEqual(other.X5c)
                ) && 
                (
                    this.Attributes == other.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.Equals(other.Attributes)
                ) && 
                (
                    this.Tags == other.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(other.Tags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.X5c != null)
                    hash = hash * 59 + this.X5c.GetHashCode();
                if (this.Attributes != null)
                    hash = hash * 59 + this.Attributes.GetHashCode();
                if (this.Tags != null)
                    hash = hash * 59 + this.Tags.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
