/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The contacts for the vault certificates.
    /// </summary>
    [DataContract]
    public partial class Contacts :  IEquatable<Contacts>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Contacts" /> class.
        /// </summary>
        /// <param name="_Contacts">The contact list for the vault certificates..</param>
        public Contacts(List<Contact> _Contacts = default(List<Contact>))
        {
            this._Contacts = _Contacts;
        }
        
        /// <summary>
        /// Identifier for the contacts collection.
        /// </summary>
        /// <value>Identifier for the contacts collection.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// The contact list for the vault certificates.
        /// </summary>
        /// <value>The contact list for the vault certificates.</value>
        [DataMember(Name="contacts", EmitDefaultValue=false)]
        public List<Contact> _Contacts { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Contacts {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  _Contacts: ").Append(_Contacts).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Contacts);
        }

        /// <summary>
        /// Returns true if Contacts instances are equal
        /// </summary>
        /// <param name="other">Instance of Contacts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Contacts other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this._Contacts == other._Contacts ||
                    this._Contacts != null &&
                    this._Contacts.SequenceEqual(other._Contacts)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this._Contacts != null)
                    hash = hash * 59 + this._Contacts.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
