/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// A Deleted Certificate consisting of its previous id, attributes and its tags, as well as information on when it will be purged.
    /// </summary>
    [DataContract]
    public partial class DeletedCertificateBundle : CertificateBundle,  IEquatable<DeletedCertificateBundle>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeletedCertificateBundle" /> class.
        /// </summary>
        /// <param name="Policy">The management policy..</param>
        /// <param name="Cer">CER contents of x509 certificate..</param>
        /// <param name="ContentType">The content type of the secret..</param>
        /// <param name="Attributes">The certificate attributes..</param>
        /// <param name="Tags">Application specific metadata in the form of key-value pairs.</param>
        public DeletedCertificateBundle(CertificatePolicy Policy = default(CertificatePolicy), byte[] Cer = default(byte[]), string ContentType = default(string), CertificateAttributes Attributes = default(CertificateAttributes), Dictionary<string, string> Tags = default(Dictionary<string, string>))
        {
            this.Policy = Policy;
            this.Cer = Cer;
            this.ContentType = ContentType;
            this.Attributes = Attributes;
            this.Tags = Tags;
        }
        
        /// <summary>
        /// The certificate id.
        /// </summary>
        /// <value>The certificate id.</value>
        [DataMember(Name="id", EmitDefaultValue=false)]
        public string Id { get; private set; }

        /// <summary>
        /// The key id.
        /// </summary>
        /// <value>The key id.</value>
        [DataMember(Name="kid", EmitDefaultValue=false)]
        public string Kid { get; private set; }

        /// <summary>
        /// The secret id.
        /// </summary>
        /// <value>The secret id.</value>
        [DataMember(Name="sid", EmitDefaultValue=false)]
        public string Sid { get; private set; }

        /// <summary>
        /// Thumbprint of the certificate.
        /// </summary>
        /// <value>Thumbprint of the certificate.</value>
        [DataMember(Name="x5t", EmitDefaultValue=false)]
        public string X5t { get; private set; }

        /// <summary>
        /// The management policy.
        /// </summary>
        /// <value>The management policy.</value>
        [DataMember(Name="policy", EmitDefaultValue=false)]
        public CertificatePolicy Policy { get; set; }

        /// <summary>
        /// CER contents of x509 certificate.
        /// </summary>
        /// <value>CER contents of x509 certificate.</value>
        [DataMember(Name="cer", EmitDefaultValue=false)]
        public byte[] Cer { get; set; }

        /// <summary>
        /// The content type of the secret.
        /// </summary>
        /// <value>The content type of the secret.</value>
        [DataMember(Name="contentType", EmitDefaultValue=false)]
        public string ContentType { get; set; }

        /// <summary>
        /// The certificate attributes.
        /// </summary>
        /// <value>The certificate attributes.</value>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public CertificateAttributes Attributes { get; set; }

        /// <summary>
        /// Application specific metadata in the form of key-value pairs
        /// </summary>
        /// <value>Application specific metadata in the form of key-value pairs</value>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeletedCertificateBundle {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Kid: ").Append(Kid).Append("\n");
            sb.Append("  Sid: ").Append(Sid).Append("\n");
            sb.Append("  X5t: ").Append(X5t).Append("\n");
            sb.Append("  Policy: ").Append(Policy).Append("\n");
            sb.Append("  Cer: ").Append(Cer).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as DeletedCertificateBundle);
        }

        /// <summary>
        /// Returns true if DeletedCertificateBundle instances are equal
        /// </summary>
        /// <param name="other">Instance of DeletedCertificateBundle to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeletedCertificateBundle other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Id == other.Id ||
                    this.Id != null &&
                    this.Id.Equals(other.Id)
                ) && 
                (
                    this.Kid == other.Kid ||
                    this.Kid != null &&
                    this.Kid.Equals(other.Kid)
                ) && 
                (
                    this.Sid == other.Sid ||
                    this.Sid != null &&
                    this.Sid.Equals(other.Sid)
                ) && 
                (
                    this.X5t == other.X5t ||
                    this.X5t != null &&
                    this.X5t.Equals(other.X5t)
                ) && 
                (
                    this.Policy == other.Policy ||
                    this.Policy != null &&
                    this.Policy.Equals(other.Policy)
                ) && 
                (
                    this.Cer == other.Cer ||
                    this.Cer != null &&
                    this.Cer.Equals(other.Cer)
                ) && 
                (
                    this.ContentType == other.ContentType ||
                    this.ContentType != null &&
                    this.ContentType.Equals(other.ContentType)
                ) && 
                (
                    this.Attributes == other.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.Equals(other.Attributes)
                ) && 
                (
                    this.Tags == other.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(other.Tags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Id != null)
                    hash = hash * 59 + this.Id.GetHashCode();
                if (this.Kid != null)
                    hash = hash * 59 + this.Kid.GetHashCode();
                if (this.Sid != null)
                    hash = hash * 59 + this.Sid.GetHashCode();
                if (this.X5t != null)
                    hash = hash * 59 + this.X5t.GetHashCode();
                if (this.Policy != null)
                    hash = hash * 59 + this.Policy.GetHashCode();
                if (this.Cer != null)
                    hash = hash * 59 + this.Cer.GetHashCode();
                if (this.ContentType != null)
                    hash = hash * 59 + this.ContentType.GetHashCode();
                if (this.Attributes != null)
                    hash = hash * 59 + this.Attributes.GetHashCode();
                if (this.Tags != null)
                    hash = hash * 59 + this.Tags.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
