/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The key update parameters.
    /// </summary>
    [DataContract]
    public partial class KeyUpdateParameters :  IEquatable<KeyUpdateParameters>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets KeyOps
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum KeyOpsEnum
        {
            
            /// <summary>
            /// Enum Encrypt for "encrypt"
            /// </summary>
            [EnumMember(Value = "encrypt")]
            Encrypt,
            
            /// <summary>
            /// Enum Decrypt for "decrypt"
            /// </summary>
            [EnumMember(Value = "decrypt")]
            Decrypt,
            
            /// <summary>
            /// Enum Sign for "sign"
            /// </summary>
            [EnumMember(Value = "sign")]
            Sign,
            
            /// <summary>
            /// Enum Verify for "verify"
            /// </summary>
            [EnumMember(Value = "verify")]
            Verify,
            
            /// <summary>
            /// Enum WrapKey for "wrapKey"
            /// </summary>
            [EnumMember(Value = "wrapKey")]
            WrapKey,
            
            /// <summary>
            /// Enum UnwrapKey for "unwrapKey"
            /// </summary>
            [EnumMember(Value = "unwrapKey")]
            UnwrapKey
        }

        /// <summary>
        /// Json web key operations. For more information on possible key operations, see JsonWebKeyOperation.
        /// </summary>
        /// <value>Json web key operations. For more information on possible key operations, see JsonWebKeyOperation.</value>
        [DataMember(Name="key_ops", EmitDefaultValue=false)]
        public List<KeyOpsEnum> KeyOps { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyUpdateParameters" /> class.
        /// </summary>
        /// <param name="KeyOps">Json web key operations. For more information on possible key operations, see JsonWebKeyOperation..</param>
        /// <param name="Attributes">Attributes.</param>
        /// <param name="Tags">Application specific metadata in the form of key-value pairs..</param>
        public KeyUpdateParameters(List<KeyOpsEnum> KeyOps = default(List<KeyOpsEnum>), KeyAttributes Attributes = default(KeyAttributes), Dictionary<string, string> Tags = default(Dictionary<string, string>))
        {
            this.KeyOps = KeyOps;
            this.Attributes = Attributes;
            this.Tags = Tags;
        }
        

        /// <summary>
        /// Gets or Sets Attributes
        /// </summary>
        [DataMember(Name="attributes", EmitDefaultValue=false)]
        public KeyAttributes Attributes { get; set; }

        /// <summary>
        /// Application specific metadata in the form of key-value pairs.
        /// </summary>
        /// <value>Application specific metadata in the form of key-value pairs.</value>
        [DataMember(Name="tags", EmitDefaultValue=false)]
        public Dictionary<string, string> Tags { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KeyUpdateParameters {\n");
            sb.Append("  KeyOps: ").Append(KeyOps).Append("\n");
            sb.Append("  Attributes: ").Append(Attributes).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KeyUpdateParameters);
        }

        /// <summary>
        /// Returns true if KeyUpdateParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of KeyUpdateParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KeyUpdateParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.KeyOps == other.KeyOps ||
                    this.KeyOps != null &&
                    this.KeyOps.SequenceEqual(other.KeyOps)
                ) && 
                (
                    this.Attributes == other.Attributes ||
                    this.Attributes != null &&
                    this.Attributes.Equals(other.Attributes)
                ) && 
                (
                    this.Tags == other.Tags ||
                    this.Tags != null &&
                    this.Tags.SequenceEqual(other.Tags)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.KeyOps != null)
                    hash = hash * 59 + this.KeyOps.GetHashCode();
                if (this.Attributes != null)
                    hash = hash * 59 + this.Attributes.GetHashCode();
                if (this.Tags != null)
                    hash = hash * 59 + this.Tags.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
