/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The key verify parameters.
    /// </summary>
    [DataContract]
    public partial class KeyVerifyParameters :  IEquatable<KeyVerifyParameters>, IValidatableObject
    {
        /// <summary>
        /// The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm.
        /// </summary>
        /// <value>The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum AlgEnum
        {
            
            /// <summary>
            /// Enum PS256 for "PS256"
            /// </summary>
            [EnumMember(Value = "PS256")]
            PS256,
            
            /// <summary>
            /// Enum PS384 for "PS384"
            /// </summary>
            [EnumMember(Value = "PS384")]
            PS384,
            
            /// <summary>
            /// Enum PS512 for "PS512"
            /// </summary>
            [EnumMember(Value = "PS512")]
            PS512,
            
            /// <summary>
            /// Enum RS256 for "RS256"
            /// </summary>
            [EnumMember(Value = "RS256")]
            RS256,
            
            /// <summary>
            /// Enum RS384 for "RS384"
            /// </summary>
            [EnumMember(Value = "RS384")]
            RS384,
            
            /// <summary>
            /// Enum RS512 for "RS512"
            /// </summary>
            [EnumMember(Value = "RS512")]
            RS512,
            
            /// <summary>
            /// Enum RSNULL for "RSNULL"
            /// </summary>
            [EnumMember(Value = "RSNULL")]
            RSNULL,
            
            /// <summary>
            /// Enum ES256 for "ES256"
            /// </summary>
            [EnumMember(Value = "ES256")]
            ES256,
            
            /// <summary>
            /// Enum ES384 for "ES384"
            /// </summary>
            [EnumMember(Value = "ES384")]
            ES384,
            
            /// <summary>
            /// Enum ES512 for "ES512"
            /// </summary>
            [EnumMember(Value = "ES512")]
            ES512,
            
            /// <summary>
            /// Enum ECDSA256 for "ECDSA256"
            /// </summary>
            [EnumMember(Value = "ECDSA256")]
            ECDSA256
        }

        /// <summary>
        /// The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm.
        /// </summary>
        /// <value>The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm.</value>
        [DataMember(Name="alg", EmitDefaultValue=false)]
        public AlgEnum? Alg { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyVerifyParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected KeyVerifyParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="KeyVerifyParameters" /> class.
        /// </summary>
        /// <param name="Alg">The signing/verification algorithm. For more information on possible algorithm types, see JsonWebKeySignatureAlgorithm. (required).</param>
        /// <param name="Digest">The digest used for signing. (required).</param>
        /// <param name="Value">The signature to be verified. (required).</param>
        public KeyVerifyParameters(AlgEnum? Alg = default(AlgEnum?), string Digest = default(string), string Value = default(string))
        {
            // to ensure "Alg" is required (not null)
            if (Alg == null)
            {
                throw new InvalidDataException("Alg is a required property for KeyVerifyParameters and cannot be null");
            }
            else
            {
                this.Alg = Alg;
            }
            // to ensure "Digest" is required (not null)
            if (Digest == null)
            {
                throw new InvalidDataException("Digest is a required property for KeyVerifyParameters and cannot be null");
            }
            else
            {
                this.Digest = Digest;
            }
            // to ensure "Value" is required (not null)
            if (Value == null)
            {
                throw new InvalidDataException("Value is a required property for KeyVerifyParameters and cannot be null");
            }
            else
            {
                this.Value = Value;
            }
        }
        

        /// <summary>
        /// The digest used for signing.
        /// </summary>
        /// <value>The digest used for signing.</value>
        [DataMember(Name="digest", EmitDefaultValue=false)]
        public string Digest { get; set; }

        /// <summary>
        /// The signature to be verified.
        /// </summary>
        /// <value>The signature to be verified.</value>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class KeyVerifyParameters {\n");
            sb.Append("  Alg: ").Append(Alg).Append("\n");
            sb.Append("  Digest: ").Append(Digest).Append("\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as KeyVerifyParameters);
        }

        /// <summary>
        /// Returns true if KeyVerifyParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of KeyVerifyParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(KeyVerifyParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Alg == other.Alg ||
                    this.Alg != null &&
                    this.Alg.Equals(other.Alg)
                ) && 
                (
                    this.Digest == other.Digest ||
                    this.Digest != null &&
                    this.Digest.Equals(other.Digest)
                ) && 
                (
                    this.Value == other.Value ||
                    this.Value != null &&
                    this.Value.Equals(other.Value)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Alg != null)
                    hash = hash * 59 + this.Alg.GetHashCode();
                if (this.Digest != null)
                    hash = hash * 59 + this.Digest.GetHashCode();
                if (this.Value != null)
                    hash = hash * 59 + this.Value.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Alg (string) minLength
            if(this.Alg != null && this.Alg.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Alg, length must be greater than 1.", new [] { "Alg" });
            }

            yield break;
        }
    }

}
