/* 
 * KeyVaultClient
 *
 * The key vault client performs cryptographic key operations and vault operations against the Key Vault service.
 *
 * OpenAPI spec version: 2016-10-01
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The storage account key regenerate parameters.
    /// </summary>
    [DataContract]
    public partial class StorageAccountRegenerteKeyParameters :  IEquatable<StorageAccountRegenerteKeyParameters>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageAccountRegenerteKeyParameters" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StorageAccountRegenerteKeyParameters() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StorageAccountRegenerteKeyParameters" /> class.
        /// </summary>
        /// <param name="KeyName">The storage account key name. (required).</param>
        public StorageAccountRegenerteKeyParameters(string KeyName = default(string))
        {
            // to ensure "KeyName" is required (not null)
            if (KeyName == null)
            {
                throw new InvalidDataException("KeyName is a required property for StorageAccountRegenerteKeyParameters and cannot be null");
            }
            else
            {
                this.KeyName = KeyName;
            }
        }
        
        /// <summary>
        /// The storage account key name.
        /// </summary>
        /// <value>The storage account key name.</value>
        [DataMember(Name="keyName", EmitDefaultValue=false)]
        public string KeyName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StorageAccountRegenerteKeyParameters {\n");
            sb.Append("  KeyName: ").Append(KeyName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as StorageAccountRegenerteKeyParameters);
        }

        /// <summary>
        /// Returns true if StorageAccountRegenerteKeyParameters instances are equal
        /// </summary>
        /// <param name="other">Instance of StorageAccountRegenerteKeyParameters to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StorageAccountRegenerteKeyParameters other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.KeyName == other.KeyName ||
                    this.KeyName != null &&
                    this.KeyName.Equals(other.KeyName)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.KeyName != null)
                    hash = hash * 59 + this.KeyName.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
